### ISSUE TITLE
no work gf after install plugin

### ISSUE THREAD

**Issue by Tuch** [burnettk/vim-angular#13]
Hi, without plugin i can press gf for string like 'my-step2.html' and it works. But now it does not work. if i use gf for services like 'layoutStorage' it works ok and file like layoutStorage.js is opening. Please help me :)

ps: gF work ok, gf - not work =(

**Comment by burnettk** [comment]
thanks for the pull request. it did break tests, though, so i can't merge it straight away. i think there are a few tests very similar to the use-case you're describing in spec/gf_file_spec.rb (i think you're looking for the plugin to preserve some of the standard functionality of gf, which will find the file under the cursor based on an exact match). ideally maybe you can add a test that describes precisely the use-case you're missing, and then fix it, but if you get all of the existing tests passing, i'll probably just merge. run the tests with ruby (bundle install and then bundle exec rake).

**Comment by burnettk** [comment]
closing stale issue. feel free to re-raise.
