### ISSUE TITLE
Finding spec file when it is alongside the source file

### ISSUE THREAD

**Issue by jrust** [burnettk/vim-angular#15]
We are following the recommendation of the angular style guide which suggests putting tests alongside the source files.  For example:
```
app/foo/foo.controller.js
app/foo/test/foo.controller.spec.js
app/bar/bar.service.js
app/bar/test/bar.service.spec.js
```

Right now doing `:A` just opens up the source file.  I tried changing a few things in the plugin source but to no avail.  

Additionally, it would be helpful in cases like this if I could specify multiple directories for the `angular_test_directory` because right now it complains about "list as string" if I set it to an array.  Thank you!

**Comment by jrust** [comment]
:clap: -- thanks!

**Comment by burnettk** [comment]
for sure, thanks for using vim-angular!
