### ISSUE TITLE
.spec.js living in same path as source file (alternate feature)

### ISSUE THREAD

**Issue by quaqua** [burnettk/vim-angular#19]
I keep my .spec.js on same level as original files. My `.vimrc` points to the same directory for tests as sources:

```
let g:angular_source_directory = ['src/app']
let g:angular_test_directory = ['src/app']
```

When I use `:A`, from my current file `my.factory.js`, I get to the same file again. This might be due to the order of precedence in `GenerateTestPaths` `plugin/angular.vim:147`. I changed the order so it returned first `l:withdotspecsuffix` and it worked:

```
return [l:withdotspecsuffix, l:withcamelcasedspecsuffix, l:samefilename]
```
Just swapping order might decrease performance for people using test/spec folders. So there might be a need for a config option (?)

**Comment by burnettk** [comment]
it passed tests so i made the update, @quaqua , thanks.
