### ISSUE TITLE
Custom Directory for Source files

### ISSUE THREAD

**Issue by Anzumana** [burnettk/vim-angular#21]
Hey,
love the plugin :)
I was wondering how i would get started in implementing my own custom directory for the source files.
We have our tests under test/unit but our javascript files for controller and services are  in
www/js/controllers
and www/js/services respectively.

**Comment by burnettk** [comment]
I think the test at https://github.com/burnettk/vim-angular/blob/master/spec/alternate_spec.rb#L60 captures your use case. If you change `WebContent/js` and `app/src` in that test to `www/js/controllers` and `www/js/services` (per your convention), it looks like you should be able to hammer `:A` and have it alternate for you. If not, write a failing test (and a fix if you can) and I'll take a look. Thanks!
