### ISSUE TITLE
Unable to find alternate file with my naming convention

### ISSUE THREAD

**Issue by scssquatch** [burnettk/vim-angular#22]
JS file: `app/assets/javascripts/angular/foos/index.controller.js.coffee`
Spec file `spec/javascripts/angular/foos/index.controller.spec.js.coffee`
Output when doing `:A` on JS file:
`Can't find file ".../spec/javascripts/angular/foos/index.controller.js_spec.coffee" in path`
Output when doing `:A` on Spec file:
`Can't find file ".../app/assets/javascripts/angular/foos/index.controller.spec.js.coffee" in path`

**Comment by scssquatch** [comment]
Is there a simple config option to change the way it looks for the alternate file?

**Comment by burnettk** [comment]
hey @scssquatch . i wrote a test (above) to show that your use case would work, except for the coffee part. :) please submit a pull request if you're willing to contribute coffee support.

**Comment by scssquatch** [comment]
Cool, thanks! I'll get working on a PR for coffee support in the near future.
